name: 'Release your project'
description: 'Perform project release with the use of bump2version and towncrier'
inputs:
  version:  # id of input
    description: 'Version to bump to'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Will create ${{ inputs.  version }}.
      shell: bash
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: ls -l
      shell: bash
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Bump
      run: bumpversion --new-version ${{ inputs.version }}
      shell: bash

