name: 'Release your project'
description: 'Perform project release with the use of bump2version and towncrier'
inputs:
  version:  # id of input
    description: 'Version to bump to'
    required: true
  user:  # id of input
    description: 'User name to commit with'
    required: true
  email:  # id of input
    description: 'User email to commit with'
    required: true
runs:
  using: "composite"
  steps:
    - name: Releaser 0.0.0
      run: echo Will create ${{ inputs.version }}.
      shell: bash
    - name: Configure
      run: |
        git config --global user.name ${{ inputs.user }}
        git config --global user.email ${{ inputs.email }}
      shell: bash
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: ls -l
      shell: bash
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - uses: actions/checkout@v3
    - run: ls -l
      shell: bash
    - name: Bump
      run: bumpversion ${{ inputs.bump_part }}
      shell: bash

