name: 'Release your project'
description: 'Perform project release with the use of bump2version and towncrier'
inputs:
  bump_part:  # id of input
    description: 'Version part to bump to'
    required: true
  user:  # id of input
    description: 'User name to commit with'
    required: true
  email:  # id of input
    description: 'User email to commit with'
    required: true
outputs:
  new-version:
    description: Nex release version
    value: ${{ steps.next-version.outputs.new-version }}
runs:
  using: "composite"
  steps:
    - name: Releaser 0.0.1
      run: echo Will bump with ${{ inputs.bump_part }} part.
      shell: bash
    - name: Configure
      run: |
        git config --global user.name ${{ inputs.user }}
        git config --global user.email ${{ inputs.email }}
      shell: bash
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: next-version
      run: ::set-output name=new-version::$(bumpversion --dry-run --list {{ inputs.bump_part }} | grep new_version | sed -r s,"^.*=",,)
      shell: bash
      # <- this will get the new version
    - uses: actions/checkout@v3
    - run: ls -l
      shell: bash
      # Here somewhere around fire towncrier
    - name: Bump
      run: bumpversion ${{ inputs.bump_part }}
      shell: bash

