name: 'Release your project'
description: 'Perform project release with the use of bump2version and towncrier'
inputs:
  bump_part:
    description: 'Version part to bump to'
    required: true
  user:
    description: 'User name to commit with'
    required: false
    default: 'Github Action'
  email:
    description: 'User email to commit with'
    required: false
    default: 'github-action@users.noreply.github.com'
  token:
    description: 'GitHub Token'
    required: true
outputs:
  new-version:
    description: Nex release version
    value: ${{ steps.next-version.outputs.new-version }}
runs:
  using: "composite"
  steps:
    - name: Releaser 0.0.2
      run: echo Will bump with ${{ inputs.bump_part }} part.
      shell: bash
    - name: Configure
      run: |
        git config --global user.name ${{ inputs.user }}
        git config --global user.email ${{ inputs.email }}
        git config --global user.password ${{ inputs.token }}
      shell: bash
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - uses: actions/checkout@v3
    - id: next-version
      run: echo "::set-output name=new-version::$(bumpversion --dry-run --list ${{ inputs.bump_part }} | grep new_version= | sed -r s,\"^.*=\",,)"
      shell: bash
      # Here somewhere around fire towncrier
    - name: Bump to ${{ steps.next-version.outputs.new-version }}
      run: bumpversion ${{ inputs.bump_part }}
      shell: bash
    - run: git push --follow-tags
      shell: bash

