name: Release test

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release this project
        id: hello
        uses: fizyk/releaser@main
        with:
          version: 0.0.1
