name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release the project with"
        required: true
        type: string
      user:
        description: "Grzegorz Śliwiński"
        required: true
        type: string
      email:
        description: "example@fizyk.github.com"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release this project
        id: hello
        uses: fizyk/releaser@main
        with:
          version: ${{ inputs.environment }}
