name: Release

on:
  workflow_dispatch:
    inputs:
      bump_part:
        description: "Version to release the project with"
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
      user:
        description: User committing
        default: 'Grzegorz Śliwiński'
        required: true
        type: string
      email:
        description: Email of the user committing
        default: 'example@fizyk.github.com'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release this project
        id: hello
        uses: fizyk/releaser@main
        with:
          bump_part: ${{ inputs.bump_part }}
